development:
  adapter: postgresql
  database: boblin_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: boblin_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: boblin_prod
  pool: 5
  timeout: 5000
